CREATE TABLE IF NOT EXISTS books (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(200) NOT NULL,
    author varchar(200) NOT NULL,
    isbn varchar(20) NOT NULL,
    image varchar(500),
    memo TEXT,
    status int NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
)