CREATE TABLE IF NOT EXISTS users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(200) NOT NULL,
    password varchar(200) NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
    )